In [4]:
import tensorflow as tf
a = tf.constant(10)
b = tf.constant(22)

with tf.Session() as sess:
    # 从正态分布中输出随机值
    _random_normal = sess.run(tf.random_normal([1,10]))
    print(_random_normal)
    # 从截断的正态分布中输出随机值
    _truncated_normal = sess.run(tf.truncated_normal([1,10]))
    print(_truncated_normal)

[[-0.26604125 -0.61854708  0.13728838  0.4313924   2.18771935  0.94398713
  -0.24663612 -0.00723609  0.95249075 -0.03784236]]
[[-0.02106814  0.82854509 -0.34243208 -0.38960502 -0.7242986  -0.67954749
  -0.83068424  0.4387362   0.86272454  0.42004889]]


In [24]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [4, 7, 1], [6, 7, 8]])
# dot 求阶乘
d = np.dot(a, b)
print(d)

l = np.array([[1, 2, 3], [4, 5, 6]])
t = np.array([[7, 8, 9], [4, 7, 1]])
# multiply 求对应位置的乘积
c = np.multiply(l, t)
print(c)


[[ 33  43  35]
 [ 84 109  89]]
[[ 7 16 27]
 [16 35  6]]
